#! /bin/bash

#if first entered value is zero print out error string
if [ -z "$1" ]; then
printf "Enter a string value"
else
echo "\$TTL	300
@	IN	SOA	ns.anwar-haidari.sb.uclllabs.be $1.anwar-haidari.sb.uclllabs.be.(
			0	; Serial
			300	; Refresh
			300	; Retry
			300	; Expire
			300)	; Negative Cashe TTL

@	IN	NS	ns.anwar-haidari.sb.uclllabs.be.

ns	IN	A	193.191.177.133
@	IN	A	193.191.177.133" > /etc/bind/zones/$1.anwar-haidari.sb.uclllabs.be

#All zones made by script should be written to named.conf.mrt-zones for easy .gitignore
echo "
zone \"$1.anwar-haidari.sb.uclllabs.be\"{
	type master;
	file \"/etc/bind/zones/$1.anwar-haidari.sb.uclllabs.be\";
	notify yes;
};" >> /etc/bind/named.conf.mrt-zones

echo "$1	IN	NS	ns.anwar-haidari.sb.uclllabs.be." >> /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be

serial_num=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
serial_lin=$(grep -Po '\s+; Serial' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
serial_all=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
new_num=$(("$serial_num" + 1))
sed -i "s/$serial_all/$new_num$serial_lin/g" /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be

rndc reload
fi
