#! /bin/bash

SUBDOMAIN=$(grep -Po '.{1,}(?=.anwar-haidari.sb.uclllabs.be)' <<< "$1")


if [ -z "$SUBDOMAIN" ];
then
	echo "Enter correct domain name"
else
	mkdir /var/www/html/$SUBDOMAIN
        touch /var/www/html/$SUBDOMAIN/index.html
        echo 'welcome '$SUBDOMAIN >> /var/www/html/$SUBDOMAIN/index.html
	touch /etc/apache2/sites-available/$SUBDOMAIN.conf

	echo  "<VirtualHost *:80>
		ServerAdmin webmaster@localhost
		ServerName $1
		DocumentRoot /var/www/html/$SUBDOMAIN
		ErrorLog \${APACHE_LOG_DIR}/$SUBDOMAIN.log
		CustomLog \${APACHE_LOG_DIR}/$SUBDOMAIN.log  combined
	</VirtualHost>" >> /etc/apache2/sites-available/$SUBDOMAIN.conf

	a2ensite $SUBDOMAIN.conf
	echo "$SUBDOMAIN	IN	A	193.191.177.133" >> /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be

	serial_num=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
	serial_lin=$(grep -Po '\s+; Serial' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
	serial_all=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be)
	new_num=$(("serial_num" + 1))
	sed -i "s/$serial_all/$new_num$serial_lin/g" /etc/bind/zones/db.anwar-haidari.sb.uclllabs.be
	systemctl reload apache2
	systemctl reload bind9
fi
